#!/bin/bash
sudo find . -type d -exec chmod 2775 {} \;
sudo find . -type f -exec chmod 664 {} \;
sudo find webroot/site/assets -type f -exec chmod 665 {} \;
sudo find webroot/site/assets -type d -exec chmod 777 {} \;
sudo git config core.sharedRepository group
sudo chmod ug+x restore-perms .git/hooks/* ./db/extract ./db/restore
